-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgxsgSsNjaxZlq+wJg
KVLFmDteCmYfKTCGnsKAx0MVmuCgCgYIKoZIzj0DAQehRANCAAQNTeMAJchKJ6Kv
hKMd0cEKOFe67eeKgVRm6p/EUfrMnJc96DsaRdihxiQ/oo/J1L8xgoG3BQFyVAQi
dF5mivzd
-----END PRIVATE KEY-----